-- Add missing columns to team_lead_data table

ALTER TABLE team_lead_data
ADD COLUMN IF NOT EXISTS full_name TEXT,
ADD COLUMN IF NOT EXISTS email TEXT,
ADD COLUMN IF NOT EXISTS phone TEXT,
ADD COLUMN IF NOT EXISTS street_address TEXT,
ADD COLUMN IF NOT EXISTS city TEXT,
ADD COLUMN IF NOT EXISTS property_state TEXT,
ADD COLUMN IF NOT EXISTS property_county TEXT,
ADD COLUMN IF NOT EXISTS zip TEXT,
ADD COLUMN IF NOT EXISTS acres DECIMAL(10, 2),
ADD COLUMN IF NOT EXISTS parcel_id TEXT,
ADD COLUMN IF NOT EXISTS dealtype TEXT,
ADD COLUMN IF NOT EXISTS notes TEXT,
ADD COLUMN IF NOT EXISTS projected_revenue DECIMAL(12, 2),
ADD COLUMN IF NOT EXISTS offer_price DECIMAL(12, 2);
