#!/bin/bash
echo "📧 Updating SendGrid email to match verified domain"
echo ""
echo "Your verified domain: em3419.parcelreach.ai"
echo "You can send from ANY @parcelreach.ai email"
echo ""
echo "Current setting in Netlify should be:"
echo "SENDGRID_FROM_EMAIL=noreply@parcelreach.ai"
echo ""
echo "OR use:"
echo "SENDGRID_FROM_EMAIL=team@parcelreach.ai"
echo ""
echo "Just make sure it's @parcelreach.ai (NOT .com)"
echo ""
echo "Then test with: bash test-invite-api.sh"
